### ISSUE TITLE
ForgeGradle 1.2 does not support forge 1.7.10

### ISSUE THREAD

**Issue by LeStegii** [anatawa12/ForgeGradle-1.2#108]
Hello,
I'm currently trying to add a feature to an old minecraft mod for 1.7.10 (HQM).
I can't get the setup to work because everytime i try to set it up, I get the following error:

`ForgeGradle 1.2 does not support forge 1.7.10`

Full log: https://pastebin.com/raw/j3Vy9Byr
Full build.gradle: https://pastebin.com/raw/jQGnU0kH

**Comment by anatawa12** [comment]
Hello.

Please specify the full version name like `1.7.10-10.13.4.1448-1.7.10`.

It had been possible to specify forge version name or build number. However few years ago, the feature was removed in original ForgeGradle before I fork. (see c2def15bd26be2f5581c6bff1ca27d7c663902f1) So, currently it's required to specify full version name (`<mcversion>-<forgeversion>`). 

It looks you're specifying forge version only. (the trailing `-1.7.10` is a part of forge version) That must be the reason of your error.

**Comment by LeStegii** [comment]
Thanks, I replaced the String like this now ^^

```diff
-   version = "10.13.4.1448-1.7.10"
+   version = "1.7.10-10.13.4.1614-1.7.10"
```
