### ISSUE TITLE
[BREAKING CHANGE] remove cauldron, mcedu, fmldev, and forgedev plugins

### ISSUE THREAD

**Issue by anatawa12** [anatawa12/ForgeGradle-1.2#14]
cauldron, mcedu, fmldev, and forgedev plugins are using AbstractTask.execute(), a internal api removed in Gradle 5.0. To upgrade this project's Gradle, I need to remove those plugins. I couldn't find project using those plugins. So I'll remove those plugin.

**Comment by ChrisJStone** [comment]
I can understand upgrading the older builds of fg to support using newer versions of gradle. However please keep in mind that not only is ForgeGradle used to build minecraft mods it is also used to build forge itself. By removing the forgedev and fmldev plugins from your fork you have now removed the ability for your fork to compile forge with a newer version of gradle.

**Comment by anatawa12** [comment]
@ChrisJStone 

> By removing the forgedev and fmldev plugins from your fork you have now removed the ability for your fork to compile forge with a newer version of gradle.

I know that fact. However, I don't have enough time to rewrite those plugin for newer Gradle because It's required to work hard to rewrite them. In my opinion, the api like `Task.execute()` will never be stable. I would like you or someone to send PR to rewrite those plugins using as less internal apis as possible.

**Comment by Worf2340** [comment]
Was there ever a solution to this? I want to use your ForgeGradle fork to rebuild Forge 1.7.10.
