### ISSUE TITLE
Amazon AWS Minecraft mirror broken

### ISSUE THREAD

**Issue by leytilera** [anatawa12/ForgeGradle-1.2#147]
The Amazon AWS Minecraft mirror which is hardcoded in Constans.java seems to be broken. `https://s3.amazonaws.com/Minecraft.Download/versions/1.7.10/1.7.10.jar` always returns `AccessDenied`

**Comment by anatawa12** [comment]
Thank you for reporting & I've checked this problem.
I want to a while (few days) for upstream to fix.
Of cource, in this period, I'll find workaround of this problem.

If you have some evidence that aws mirror is closed (I mean it will never came again), Please let me know. I'll make workaround quickly.

**Comment by anatawa12** [comment]
Relates https://github.com/itzg/docker-minecraft-server/issues/1814

**Comment by leytilera** [comment]
I don't know, if the aws mirror is closed, but newer versions of ForgeGradle seem to download the Minecraft files from piston meta using this endpoint: `https://piston-meta.mojang.com/mc/game/version_manifest.json`

**Comment by jediexe** [comment]
Broken for me as well. Not sure if it's closed or how long it would take for them to notice if it's just broken.

**Comment by anatawa12** [comment]
I'm going to fix this problem soon with @leytilera's suggestion. Thank you for suggestion.

**Comment by anatawa12** [comment]
#148 implemented fix for 1.1.x and #149 for 1.0.x. I'm going to release 1.0.10.

**Comment by anatawa12** [comment]
1.2-1.0.10 has been released. Please try it.

**Comment by DakEnviy** [comment]
The fix works fine. Thank you!
