### ISSUE TITLE
Empty original package directories after applying minecraft.srgExtra "PK: A B"

### ISSUE THREAD

**Issue by MJaroslav** [anatawa12/ForgeGradle-1.2#151]
Reproduction:

1. Make sure for having any `original.package` package after mod jar building..
2. Add extra package relocation to `reobf` task by `minecraft {}` block:
```gradle
minecraft {
    srgExtra "PK: original/package new/package"
}
```
4. Open build output jar and you will see empty directories of `original/package` and applied relocation with `new/package`.

**Expected behavior:** Jar must be without original package directories.

It's https://github.com/md-5/SpecialSource problem and I fixed it in https://github.com/md-5/SpecialSource/pull/76, but the author has not yet released any release with this PR.

I also fixed it in another FG fork by wrapping of remapper from SpecialSource: https://github.com/juanmuscaria/ForgeGradle/pull/9, but I prefer your fork for half a year already.

This problem not "very dangerous" or something, but very annoying for me.

**Comment by anatawa12** [comment]
I'm going to fork SpecialSource & release fork of SpecialSource, and then I'll release newer version.
