### ISSUE TITLE
unable to setupCIworkspace, cursecdn.com seems down?

### ISSUE THREAD

**Issue by kuzuanpa** [anatawa12/ForgeGradle-1.2#154]
When I setup my develop environment, I got these errors:

* What went wrong:
Could not resolve all files for configuration ':userDevPackageDepConfig'.
> Could not resolve net.minecraftforge:forge:1.7.10-10.13.4.1614-1.7.10.
  Required by:
      project :
   > Could not resolve net.minecraftforge:forge:1.7.10-10.13.4.1614-1.7.10.
      > Could not get resource 'http://addons-origin.cursecdn.com/files/2246/919/net.minecraftforge/forge/1.7.10-10.13.4.1614-1.7.10/ivy-1.7.10-10.13.4.1614-1.7.10.xml'.
         > Could not GET 'http://addons-origin.cursecdn.com/files/2246/919/net.minecraftforge/forge/1.7.10-10.13.4.1614-1.7.10/ivy-1.7.10-10.13.4.1614-1.7.10.xml'. Received status code 530 from server: 

I've  solved the s3.amazonaws.com problem by manually setup a http server containing all files needed to setup my workspace (files download from mirror sites) ,well it do solve the problems when downloadClient and downloadServer, but when things came to this period ,I cannot find any mirror containing this file. 
I try to access addons-origin.cursecdn.com directly using wget and firefox. wget gives same error and firefox give out a page says I successfully connected to cloudflare but they cannot contact the origin website.
I guess it maybe a temporarily down, but i wait for 2 days and still no luck.
The addons-origin.cursecdn.com seems to be hardcoded in buildscript or something.
(several class file founded when using grep : Binary file scripts/3hqzfuh74gga97sitp2chb7oj/proj/projc2a6a4e5c498062f73e38586711c2070/classes/_BuildScript_$_run_closure3$_closure8.class matches)
Any solution to this? thanks a lot to you!

**Comment by anatawa12** [comment]
I think cursecdn is not (directly) used in this FG. Can you show me the build.gradle?

**Comment by kuzuanpa** [comment]
well it's a fork of AdvancedRocketry,and there are 2 
build.gradle file.
libVulpe:
[build.gradle.txt](https://github.com/anatawa12/ForgeGradle-1.2/files/10046052/build.gradle.txt)
AdvancedRocketry:
[build.gradle.txt](https://github.com/anatawa12/ForgeGradle-1.2/files/10046056/build.gradle.txt)


AdvancedRocketry project page:
https://github.com/Advanced-Rocketry/AdvancedRocketry/tree/MC1.7

**Comment by anatawa12** [comment]
It looks because of your build.gradle file and not a problem of ForgeGradle. 
The cursecdn is specified in your gradle file and not used in ForgeGradle.
If you upgraded Gradle, you may need to fix gradle file. Even if you didn't change it, upstream (cuesecdn) change may broke your build.

**Comment by kuzuanpa** [comment]
well I forgot to search that link in build.gradle. sorry!
