### ISSUE TITLE
JAR not downloading

### ISSUE THREAD

**Issue by XEN486** [anatawa12/ForgeGradle-1.2#166]
Minecraft.Download at amazonaws is offline but it is still trying to download from it which causes my entire project to just fail, please try to find a different way to get the jars and jsons

**Comment by anatawa12** [comment]
1.2-1.0.11 should fixed this problem. Can you check your ForgeGradle version?

**Comment by XEN486** [comment]
do I have to change anything different to the forgegradle example project's setup?

**Comment by XEN486** [comment]
to get the new update*

**Comment by XEN486** [comment]
gradlew says:
#################################################
         ForgeGradle 1.2.2-g2ea0336
  https://github.com/MinecraftForge/ForgeGradle
#################################################
               Powered by MCP unknown
             http://modcoderpack.com
         by: Searge, ProfMobius, Fesh0r,
         R4wk, ZeuX, IngisKahn, bspkrs
#################################################

should the splash be changed? if so then it looks like the fork hasn't applied for some reason?

**Comment by XEN486** [comment]
nevermind, got it to work, for some reason my gradle-wrapper was set to gradle 1.12, after fixing that your fork works properly!

**Comment by anatawa12** [comment]
According to your comment, you're using official ForgeGradle (or too old (1.0.3 or older) version of my fork of ForgeGradle).
This repository is for anatawa12's fork of forgeGradle. Please use my fork before opening issue here!
https://github.com/anatawa12/ForgeGradle-1.2/blob/df67aa558695898c04dd3cb919eb46bfb3dd924b/src/main/java/net/minecraftforge/gradle/common/BasePlugin.java#L196-L206
