### ISSUE TITLE
Some mappings are missing

### ISSUE THREAD

**Issue by iocmet** [anatawa12/ForgeGradle-1.2#207]
There is some mappings missing, for example func_145771_j that is pushOutOfBlocks
![image](https://github.com/anatawa12/ForgeGradle-1.2/assets/63492966/d01d1bbd-feef-47b7-9898-c2bacb1e1010)
![image](https://github.com/anatawa12/ForgeGradle-1.2/assets/63492966/74e1fbe2-3886-4f94-8ca2-d2d3e9a2cbb3)

**Comment by anatawa12** [comment]
I think it depends on the mapping version so declare to use mapping version you want to use in `minecraft` block.

**Comment by iocmet** [comment]
It not works though

**Comment by anatawa12** [comment]
Which version of MCP are you using?
AFAIK, default mapping version for Forge 1614 does not include `func_145771_j` => `pushOutOfBlocks` mapping and I don't know which version of MCP does include that mapping.
In addition, you must re-setup workspace.

Due to lack of information on your issue, I assume that the issue is that `func_145771_j` is not renamed to `pushOutOfBlocks` and I think it's expected behavior.

If this is not true, please describe the following:
- What's wrong.
- Steps to reproduce (including versions of plugins)

**Comment by iocmet** [comment]
> Which version of MCP are you using? AFAIK, default mapping version for Forge 1614 does not include `func_145771_j` => `pushOutOfBlocks` mapping and I don't know which version of MCP does include that mapping. In addition, you must re-setup workspace.
> 
> Due to lack of information on your issue, I assume that the issue is that `func_145771_j` is not renamed to `pushOutOfBlocks` and I think it's expected behavior.
> 
> If this is not true, please describe the following:
> 
> * What's wrong.
> * Steps to reproduce (including versions of plugins)

What you mean by mcp version? anyway mcp 908 not includes this mappings though
There is for 1.7.10, you can see here https://mcp.thiakil.com/

In forgeBin some methods and fields is not deobfuscated
![image](https://github.com/anatawa12/ForgeGradle-1.2/assets/63492966/82039257-8a04-4f06-9dce-521b01c36d29)
![image](https://github.com/anatawa12/ForgeGradle-1.2/assets/63492966/2e2eebf6-f13a-453f-b103-3d1e500393f9)
![image](https://github.com/anatawa12/ForgeGradle-1.2/assets/63492966/43f6489e-7684-42b8-96d7-98929f666ae1)

Setup minimal forgegradle workspace and then try reference any of this in code (like entity.func_145781_i)

**Comment by anatawa12** [comment]
> What you mean by mcp version?

Sorry for not being clear. I mean mcp srg to mcp name mapping version. There are some stable versions and tons of snapshot versions.

https://maven.minecraftforge.net/de/oceanlabs/mcp/mcp_snapshot/maven-metadata.xml
https://maven.minecraftforge.net/de/oceanlabs/mcp/mcp_stable/maven-metadata.xml

> There is for 1.7.10, you can see here https://mcp.thiakil.com/

thank you for providingsource of the mapping but the site looks broken. it redirects Infinity (at least 20 times).

Regardless the website is alive or not, the reason why the method is not renamed must be that mapping version difference.

**Comment by iocmet** [comment]
Site works for me, try web proxy like https://www.croxyproxy.com/ or other browser
But i tried set latest (12) and channel stable

**Comment by anatawa12** [comment]
How about newer snapshot versions?
Or the site might use their own original mapping.

**Comment by anatawa12** [comment]
I confirmed the mapping is exists in stable_12 channel but it doesn't included in the forge 1614 default mappong version (IDK name of the default version).

Specifying mapping version you want to use in build.gradle with `minecraft { mappings = "stable_12" }` and re-running `./gradlew setupDevWorkspace` should fix this problem.

**Comment by anatawa12** [comment]
@iocmet Could you try `minecraft { mappings = "stable_12" }` and re-setup workspace?

I confirmed this works in my environment.

<img width="1299" alt="image" src="https://github.com/anatawa12/ForgeGradle-1.2/assets/22656849/61a4d8a2-cd9c-4f3c-8c2a-46280ef3e44c">

**Comment by iocmet** [comment]
Sorry for not responding, looks like it works fine with stable_12, i think it not worked for me before because i tried specify version and channel with mappingsChannel and mappingsVersion and customVersion and mappingsSet left unspecified, i can close issue i think
![image](https://github.com/anatawa12/ForgeGradle-1.2/assets/63492966/383f5858-2c7e-4a6c-8aa8-dc97005d5a8a)
