### ISSUE TITLE
Make "copyEmptyDirectories = false" optional

### ISSUE THREAD

**Issue by iocmet** [anatawa12/ForgeGradle-1.2#211]
[Here](https://github.com/anatawa12/ForgeGradle-1.2/blob/9f771fde8633b396daa9cc69a2ab383c0ea4d2f4/src/main/java/net/minecraftforge/gradle/tasks/user/reobf/ObfArtifact.java#L371) forgegradle sets copyEmptyDirectories to false that causes SpecialSource not add directory entries to obfuscated jar, this causes getResource to return null on folders in mods (for example, WarpDrive checks if directory exists with getResource [here](https://github.com/LemADEC/WarpDrive/blob/90abf4fcde95537419275a2beb30fc8ec3fbb27b/src/main/java/cr0s/warpdrive/block/TileEntityAbstractInterfaced.java#L103))

**Comment by iocmet** [comment]
Any progress on this?

**Comment by anatawa12** [comment]
I think adding option to toggle is good but I don't have enough time to implement that. PullRequests are welcome and I can release

**Comment by iocmet** [comment]
Ok

**Comment by MJaroslav** [comment]
Sorry, my bad (#151) :sweat_smile:

**Comment by MJaroslav** [comment]
I fix it in #213.

/Why hash mentions not work in PR titles?/
