### ISSUE TITLE
Annoying forge maven warning

### ISSUE THREAD

**Issue by MJaroslav** [anatawa12/ForgeGradle-1.2#214]
It's can't be disabled by your custom system property and ignores correct maven repository URL.

I think cause in this logic (may be add NOT to second condition?):

https://github.com/anatawa12/ForgeGradle-1.2/blob/fa4b883e833deda50b1047b934c03518ec0649da/src/main/java/net/minecraftforge/gradle/common/BasePlugin.java#L215-L216C30

**Comment by anatawa12** [comment]
> may be add NOT to second condition?

Yes. Sorry for mistake.
