### ISSUE TITLE
Is there a way to use old mcp mappings?

### ISSUE THREAD

**Issue by Sputchik** [anatawa12/ForgeGradle-1.2#216]
HIIIIIIIIIII!

As title says, is it possible to use old mcp mappings to not having exceptions when building mod? 

What to install, change, downgrade, where?

Or every .java file has to be modified using new mappings? 

Thanks!!!! :)
![Screenshot 2024-01-31 134043](https://github.com/anatawa12/ForgeGradle-1.2/assets/138970407/3665f067-6fd0-4fe0-9076-b11f565d4c12)

**Comment by anatawa12** [comment]
- Using older version of forge may fix the problem
- If you know which version of mcp is used, `minecraft.mappings = "mapping_version"` (mapping version is like `stable_12`) will force FG to use specified mcp version

**Comment by Sputchik** [comment]
thanks for your reply! :)

While any forge src version did not directly change mappings, it seems only new mcp version is used. I don't really know where i should put minecraft.mappings value you typed, in build.gradle or elsewhere. am i looking at mcp you talking about: http://www.modcoderpack.com ?

**Comment by Sputchik** [comment]
> * Using older version of forge may fix the problem
> 
>     * If you know which version of mcp is used, `minecraft.mappings = "mapping_version"` (mapping version is like `stable_12`) will force FG to use specified mcp version

thanks for your reply! :)

While any forge src version did not directly change mappings, it seems only new mcp version is used. I don't really know where i should put minecraft.mappings value you typed, in build.gradle or elsewhere. am i looking at mcp you talking about: http://www.modcoderpack.com ?

**Comment by Sputchik** [comment]
thanks for your reply! :)

While any forge src version did not directly change mappings, it seems only new mcp version is used. I don't really know where i should put minecraft.mappings value you typed, in build.gradle or elsewhere. am i looking at mcp you talking about: http://www.modcoderpack.com ? 

> * Using older version of forge may fix the problem
> 
>     * If you know which version of mcp is used, `minecraft.mappings = "mapping_version"` (mapping version is like `stable_12`) will force FG to use specified mcp version

thanks for your reply! :)

While any forge src version did not directly change mappings, it seems only new mcp version is used. I don't really know where i should put minecraft.mappings value you typed, in build.gradle or elsewhere. am i looking at mcp you talking about: http://www.modcoderpack.com ?
