### ISSUE TITLE
1.7.10 failed: Read timed out

### ISSUE THREAD

**Issue by JoJoServer** [anatawa12/ForgeGradle-1.2#218]
does not go beyond the download https://maven.minecraftforge.net/com/anatawa12/forge/ForgeGradle/maven-metadata.xml
`> Could not resolve all files for configuration ':classpath'.
   > Could not resolve com.anatawa12.forge:ForgeGradle:1.2-1.0.+.
     Required by:
         project :
      > Could not resolve com.anatawa12.forge:ForgeGradle:1.2-1.0.+.
         > Failed to list versions for com.anatawa12.forge:ForgeGradle.
            > Unable to load Maven meta-data from https://maven.minecraftforge.net/com/anatawa12/forge/ForgeGradle/maven-metadata.xml.
               > Could not get resource 'https://maven.minecraftforge.net/com/anatawa12/forge/ForgeGradle/maven-metadata.xml'.
                  > Could not GET 'https://maven.minecraftforge.net/com/anatawa12/forge/ForgeGradle/maven-metadata.xml'.
                     > Connect to maven.minecraftforge.net:443 [maven.minecraftforge.net/172.67.161.211, maven.minecraftforge.net/104.21.58.163, maven.minecraftforge.net/2606:4700:3036:0:0:0:ac43:a1d3, maven.minecraftforge.net/2606:4700:3032:0:0:0:6815:3aa3] failed: Read timed out` 
                     
                     build.gradle
`buildscript {
    repositories {
        mavenCentral()
        maven {
            name = "forge"
            url = "https://maven.minecraftforge.net/"
        }
        maven {
            name = "sonatype"
            url = "https://oss.sonatype.org/content/repositories/snapshots/"
        }
    }
    dependencies {
        classpath ('com.anatawa12.forge:ForgeGradle:1.2-1.0.+') {
                       changing = true
                  }
    }
}

apply plugin: 'forge'

targetCompatibility = sourceCompatibility = JavaVersion.VERSION_1_8

version = "1.0"
group= "com.yourname.modid" // http://maven.apache.org/guides/mini/guide-naming-conventions.html
archivesBaseName = "modid"

minecraft {
    version = "1.7.10-10.13.4.1614-1.7.10"
    runDir = "eclipse"
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

dependencies {
    // you may put jars on which you depend on in ./libs
    // or you may define them like so..
    //compile "some.group:artifact:version:classifier"
    //compile "some.group:artifact:version"
      
    // real examples
    //compile 'com.mod-buildcraft:buildcraft:6.0.8:dev'  // adds buildcraft to the dev env
    //compile 'com.googlecode.efficient-java-matrix-library:ejml:0.24' // adds ejml to the dev env

    // for more info...
    // http://www.gradle.org/docs/current/userguide/artifact_dependencies_tutorial.html
    // http://www.gradle.org/docs/current/userguide/dependency_management.html

}

processResources
{
    // this will ensure that this task is redone when the versions change.
    inputs.property "version", project.version
    inputs.property "mcversion", project.minecraft.version

    // replace stuff in mcmod.info, nothing else
    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'
                
        // replace version and mcversion
        expand 'version':project.version, 'mcversion':project.minecraft.version
    }
        
    // copy everything else, thats not the mcmod.info
    from(sourceSets.main.resources.srcDirs) {
        exclude 'mcmod.info'
    }
}`

**Comment by anatawa12** [comment]
Could you re-post your error message and your build script surrounding with ` ``` `?
I could not figure out what is the actual your code.

We can use `` ` `` only for single-line contents. We have to use ` ``` ` for multi-line code quote like this:

````md

```
long code
   here
```
````

**Comment by JoJoServer** [comment]
oh sorry build.gradle  
```
buildscript {
    repositories {
        mavenCentral()
        maven {
            name = "forge"
            url = "https://maven.minecraftforge.net/"
        }
        maven {
            name = "sonatype"
            url = "https://oss.sonatype.org/content/repositories/snapshots/"
        }
    }
    dependencies {
        classpath ('com.anatawa12.forge:ForgeGradle:1.2-1.0.+') {
                       changing = true
                  }
    }
}

apply plugin: 'forge'

targetCompatibility = sourceCompatibility = JavaVersion.VERSION_1_8

version = "1.0"
group= "com.yourname.modid" // http://maven.apache.org/guides/mini/guide-naming-conventions.html
archivesBaseName = "modid"

minecraft {
    version = "1.7.10-10.13.4.1614-1.7.10"
    runDir = "eclipse"
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

dependencies {
    // you may put jars on which you depend on in ./libs
    // or you may define them like so..
    //compile "some.group:artifact:version:classifier"
    //compile "some.group:artifact:version"
      
    // real examples
    //compile 'com.mod-buildcraft:buildcraft:6.0.8:dev'  // adds buildcraft to the dev env
    //compile 'com.googlecode.efficient-java-matrix-library:ejml:0.24' // adds ejml to the dev env

    // for more info...
    // http://www.gradle.org/docs/current/userguide/artifact_dependencies_tutorial.html
    // http://www.gradle.org/docs/current/userguide/dependency_management.html

}

processResources
{
    // this will ensure that this task is redone when the versions change.
    inputs.property "version", project.version
    inputs.property "mcversion", project.minecraft.version

    // replace stuff in mcmod.info, nothing else
    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'
                
        // replace version and mcversion
        expand 'version':project.version, 'mcversion':project.minecraft.version
    }
        
    // copy everything else, thats not the mcmod.info
    from(sourceSets.main.resources.srcDirs) {
        exclude 'mcmod.info'
    }
}

```

**Comment by anatawa12** [comment]
Could you with the error message again?

**Comment by JoJoServer** [comment]
I was away on business, now I'm back, I launched my project and miraculously it was successfully compiled after downloading all the resources, I don't understand how it happened, but it works!

**Comment by anatawa12** [comment]
In my opinion, the forge's server is partially down at the time you tried. I think it's not a issue of my side.
