### ISSUE TITLE
how to build?

### ISSUE THREAD

**Issue by darallium** [anatawa12/ForgeGradle-1.2#8]

**Comment by darallium** [comment]
I saw the document but not found https://forgegradle.readthedocs.io/en/latest/reference/tasks/, these tasks in anywhere.

**Comment by anatawa12** [comment]
What do you mean? Do you want to build ForgeGradle-1.2 or your mod with ForgeGradle-1.2?

**Comment by darallium** [comment]
Yes．
I want to build Forge-gradle
 I read the Document but I cant undersand

**Comment by anatawa12** [comment]
Those tasks shown in your link are for building your mod with ForgeGradle 1.2. ForgeGradle is a Gradle Plugin which adds some tasks and in your link, there are documentations about some tasks added by ForgeGradle and some Gradle tasks.

If you want to build ForgeGradle, you can just build this project as a simple Gradle project, this means just execute `./gradlew build`.

**Comment by anatawa12** [comment]
No response for long time. Closing this issue.
