### ISSUE TITLE
gradlew build stopped working

### ISSUE THREAD

**Issue by hohserg1** [anatawa12/ForgeGradle-1.2#87]
I have a some workspace which was working.
Today I try to execute `gradlew build` and got follor log:

```
PS C:\Users\hohserg\Documents\modding\Test> .\gradlew.bat build

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'Test'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve org.eclipse.platform:org.eclipse.equinox.common:[3.14.0,4.0.0).
     Required by:
         project : > com.anatawa12.forge:ForgeGradle:1.2-1.0.6 > net.minecraftforge:Srg2Source:4.2.7 > org.eclipse.jdt:org.eclipse.jdt.core:3.14.0 > org.eclipse.platform:org.eclipse.core.runtime:3.20.100
         project : > com.anatawa12.forge:ForgeGradle:1.2-1.0.6 > net.minecraftforge:Srg2Source:4.2.7 > org.eclipse.jdt:org.eclipse.jdt.core:3.14.0 > org.eclipse.platform:org.eclipse.core.runtime:3.20.100 > org.eclipse.platform:org.eclipse.equinox.registry:3.10.100
      > Failed to list versions for org.eclipse.platform:org.eclipse.equinox.common.
         > Unable to load Maven meta-data from https://files.minecraftforge.net/maven/org/eclipse/platform/org.eclipse.equinox.common/maven-metadata.xml.
            > Could not get resource 'https://files.minecraftforge.net/maven/org/eclipse/platform/org.eclipse.equinox.common/maven-metadata.xml'.
               > Could not GET 'https://maven.minecraftforge.net/org/eclipse/platform/org.eclipse.equinox.common/maven-metadata.xml'. Received status code 500 from server: Internal Server Error

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 17s
PS C:\Users\hohserg\Documents\modding\Test>
```

How to fix?

**Comment by hohserg1** [comment]
Ok, I tried to run with `--offline` and it work...

**Comment by anatawa12** [comment]
In short, I'll wait and see for a few days.
I think it's Forge Development Team's mistake. Please use --offline with caches as a workaround. 
If there's no update by ForgeDevTeam for a long time, I'll do something.

THIS WAS FIXED

**Comment by DRKV333** [comment]
Well, it  still doesn't work, but instead of `500 Internal Server Error`, it's now a `422 Unprocessable Entity`...

**Comment by anatawa12** [comment]
@DRKV333 Can you show me the error message? [CI] works well so I think there's no errors from forge's maven server

[CI]: https://github.com/anatawa12/ForgeGradle-1.2/runs/2880340656

**Comment by DRKV333** [comment]
Yeah, sorry, it's actually working fine fine now. I was trying to get someone else's mod to build, and there were some other problems with the configuration.

**Comment by anatawa12** [comment]
@DRKV333
>  I was trying to get someone else's mod to build, and there were some other problems with the configuration.

If your problems looks problems of this ForgeGradle, plesae make a new issue.

It looks this issue had been resolved so I'll close this issue.
